#!/usr/bin/env python3
"""
build.py — Verilator build script for MSYS2/Windows
Bypasses verilated.mk path issues by compiling directly.
Usage: python build.py <module_name> <top_module> <tb_cpp> <rtl_src1> [rtl_src2 ...]
"""
import subprocess, sys, os, glob, shutil

BASH      = r"C:\msys64\usr\bin\bash.exe"
VL_ROOT   = "/mingw64/share/verilator"
VL_INC    = f"{VL_ROOT}/include"
CXX       = "g++"
CXXFLAGS  = f"-Os -faligned-new -fcf-protection=none -pthread"
WARNFLAGS = (" -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow "
             "-Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare "
             "-Wno-uninitialized -Wno-unused-but-set-parameter "
             "-Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable")

def bash(cmd, **kw):
    """Run a command inside MSYS2 bash with MSYS_NO_PATHCONV."""
    return subprocess.run([BASH, "-c", cmd], capture_output=True, text=True, **kw)

def main():
    if len(sys.argv) < 5:
        print(f"Usage: {sys.argv[0]} module_name top_module tb_cpp rtl_src1 [rtl_src2 ...]")
        sys.exit(1)

    mod_name  = sys.argv[1]
    top_mod   = sys.argv[2]
    tb_cpp    = sys.argv[3]
    rtl_files = sys.argv[4:]

    here = os.path.dirname(os.path.abspath(__file__))
    os.chdir(here)

    # Step 1: Verilate
    print("=== Verilator --cc ===")
    rtl_args = " ".join(f"../../{f}" for f in rtl_files)
    cmd = (f'export PATH=/mingw64/bin:/usr/bin:$PATH; export MSYS_NO_PATHCONV=1; '
           f'export VERILATOR_ROOT={VL_ROOT}; '
           f'cd /d/workspace/fpgalpu/rtl/sim/verilator && '
           f'rm -rf obj_dir && '
           f'verilator --cc -I../../include {rtl_args} '
           f'--top-module {top_mod} --exe {tb_cpp} '
           f'-Wno-WIDTH -Wno-LITENDIAN')
    r = bash(cmd)
    if r.returncode != 0:
        print("STDERR:", r.stderr)
        print("STDOUT:", r.stdout)
        sys.exit(1)
    print(r.stdout)

    # Step 2: Build the combined source list
    obj_dir = os.path.join(here, "obj_dir")
    if not os.path.isdir(obj_dir):
        print("ERROR: obj_dir not created")
        sys.exit(1)

    # Gather all generated .cpp and .h files
    cpp_files = sorted(glob.glob(os.path.join(obj_dir, f"{top_mod}*.cpp")))
    all_cpp   = os.path.join(obj_dir, f"{top_mod}__ALL.cpp")

    with open(all_cpp, "w") as f:
        f.write("// Combined Verilator sources (auto-generated by build.py)\n")
        for cpp in cpp_files:
            base = os.path.basename(cpp)
            if base == os.path.basename(all_cpp):
                continue
            f.write(f'#include "{base}"\n')
    print(f"Generated {all_cpp} with {len(cpp_files)} sources")

    # Step 3: Compile using the MSYS2 g++
    vl_inc_win  = r"C:\msys64\mingw64\share\verilator\include"
    vl_inc_vlt  = vl_inc_win + r"\vltstd"
    defines     = "-DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0"

    obj_dir_abs = os.path.abspath(obj_dir)
    include_flags = f"-I{obj_dir_abs} -I{vl_inc_win} -I{vl_inc_vlt}"
    all_flags     = f"{CXXFLAGS}{WARNFLAGS} {defines} {include_flags}"

    objects = []
    for src, obj_name in [
        (os.path.join(here, tb_cpp), "tb_main.o"),
        (os.path.join(vl_inc_win, "verilated.cpp"), "verilated.o"),
        (os.path.join(vl_inc_win, "verilated_threads.cpp"), "verilated_threads.o"),
        (all_cpp, "combined.o"),
    ]:
        obj = os.path.join(obj_dir_abs, obj_name)
        print(f"Compiling {src}...")
        r = subprocess.run(
            f'"{CXX}" {all_flags} -c -o "{obj}" "{src}"',
            shell=True, capture_output=True, text=True, cwd=here)
        if r.returncode != 0:
            print("Compile error:", r.stderr)
            sys.exit(1)
        objects.append(obj)

    # Step 4: Link
    exe = os.path.join(obj_dir_abs, top_mod)
    print(f"Linking {exe}...")
    obj_str = " ".join(f'"{o}"' for o in objects)
    r = subprocess.run(
        f'"{CXX}" {obj_str} -pthread -lpthread -latomic -o "{exe}"',
        shell=True, capture_output=True, text=True, cwd=here)
    if r.returncode != 0:
        print("Link error:", r.stderr)
        sys.exit(1)

    print(f"\nBuild complete: {exe}")
    print("Run with:", exe)

if __name__ == "__main__":
    main()
