#!/usr/bin/env python3
"""Golden model for layer_compute_engine (RMS→Router→FFN→RMS) using RTL-matched arithmetic."""

import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from gen_ffn_tb_vectors import (FP4_LUT, fp4_q12, fp8_q8, mac_product, silu_q12,
    q12_to_fp8, linear, pack_values, flatten_beats, flatten_weight_rows)

HIDDEN, INTER, LANES, K_BEATS, SQRT_ITERS = 8, 4, 4, 2, 3


def rtl_isqrt(a):
    if a == 0: return 1
    lead = a.bit_length() - 1
    g = 1 << (lead >> 1)
    for _ in range(SQRT_ITERS):
        g = (g + a // g) >> 1
    return g


def rtl_rms_norm(x_q12, gamma_q12):
    sum_x2 = sum(v * v for v in x_q12)
    mean = sum_x2 // HIDDEN
    rsqrt = 16777216 // rtl_isqrt(mean)
    return [((v * g) >> 12) * rsqrt >> 12 for v, g in zip(x_q12, gamma_q12)]


def rtl_router(scores_q12):
    best_s, best_i = -10**18, 0
    second_s, second_i = -10**18, 0
    for i, s in enumerate(scores_q12):
        if s > best_s:
            second_s, second_i = best_s, best_i
            best_s, best_i = s, i
        elif s > second_s:
            second_s, second_i = s, i
    return [best_i, second_i], [best_s, second_s]


def layer_golden(input_q12, gate_weights, up_weights, down_weights, gamma_q12, rtr_weights):
    # RMSNorm1
    r1_out = rtl_rms_norm(input_q12, gamma_q12)

    # Router
    router_scores = []
    for e in range(len(rtr_weights)):
        acc = 0
        for i in range(HIDDEN):
            acc += r1_out[i] * rtr_weights[e][i]
        router_scores.append(acc)
    top_idx, top_sc = rtl_router(router_scores)

    # Encode RMS1 output to fp8 for FFN
    r1_f8 = [q12_to_fp8(v) for v in r1_out]

    # FFN gate/up/down
    gate = linear(gate_weights, [r1_f8[0:4], r1_f8[4:8]], (0x38, 0x38))
    up = linear(up_weights, [r1_f8[0:4], r1_f8[4:8]], (0x38, 0x38))
    mid_q12 = []
    mid_f8 = []
    for g, u in zip(gate, up):
        g_s = g - (1 << 32) if g & 0x80000000 else g
        u_s = u - (1 << 32) if u & 0x80000000 else u
        m = (silu_q12(g_s) * u_s) >> 12
        mid_q12.append(m)
        mid_f8.append(q12_to_fp8(m))
    down_out = linear([[row] for row in down_weights], [mid_f8], (0x38,))

    # RMSNorm2
    r2_out = rtl_rms_norm(down_out, gamma_q12)

    return r2_out, top_idx, top_sc, r1_out


def pack_case(name, input_q12, gate_w, up_w, down_w, gamma_q12, rtr_w, expected):
    lines = []
    lines.append(f"    localparam logic [{HIDDEN*32}-1:0] {name}_IN_PACK = {pack_values(input_q12, 32)};")
    lines.append(f"    localparam logic [{INTER*K_BEATS*LANES*4}-1:0] {name}_GATE_PACK = {pack_values(flatten_weight_rows(gate_w), 4)};")
    lines.append(f"    localparam logic [{INTER*K_BEATS*LANES*4}-1:0] {name}_UP_PACK = {pack_values(flatten_weight_rows(up_w), 4)};")
    lines.append(f"    localparam logic [{HIDDEN*LANES*4}-1:0] {name}_DOWN_PACK = {pack_values(flatten_beats(down_w), 4)};")
    flat_rtr = [v for row in rtr_w for v in row]
    lines.append(f"    localparam logic [{len(flat_rtr)*32}-1:0] {name}_RTR_PACK = {pack_values(flat_rtr, 32)};")
    lines.append(f"    localparam logic [{HIDDEN*32}-1:0] {name}_EXPECTED_PACK = {pack_values(expected, 32)};")
    return lines


def main():
    # Case 0: all 1.0 input, identity weights → router=[0,1], output ~5793
    act0 = [4096]*8
    gamma0 = [4096]*8
    gate0 = [[[0x4, 0x0, 0x0, 0x0], [0x0]*4] for _ in range(INTER)]  # single lane +1.0
    up0 = [[[0x4, 0x0, 0x0, 0x0], [0x0]*4] for _ in range(INTER)]
    down0 = [[0x0]*4 for _ in range(HIDDEN)]
    for r in range(INTER): down0[r][r] = 0x4
    rtr0 = [[4096 if i == e else 0 for i in range(HIDDEN)] for e in range(4)]

    exp0, top0, top_sc0, r1_0 = layer_golden(act0, gate0, up0, down0, gamma0, rtr0)

    # Case 1: mixed-sign input, same weights
    act1 = [4096, 2048, 0, -2048, -4096, -2048, 0, 2048]
    exp1, top1, top_sc1, r1_1 = layer_golden(act1, gate0, up0, down0, gamma0, rtr0)

    lines = []
    lines.append("// AUTO-GENERATED by scripts/simulation/gen_layer_golden.py")
    lines.append("package tb_layer_golden_pkg;")
    lines.append(f"    localparam int HIDDEN = {HIDDEN}; localparam int INTER = {INTER};")
    lines.append(f"    localparam int LANES = {LANES}; localparam int K_BEATS = {K_BEATS};")
    lines.extend(pack_case("C0", act0, gate0, up0, down0, gamma0, rtr0, exp0))
    lines.append("")
    lines.extend(pack_case("C1", act1, gate0, up0, down0, gamma0, rtr0, exp1))
    lines.append("endpackage")

    out = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "rtl", "sim", "tb_layer_golden_pkg.sv"))
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out}")
    print(f"C0 expected: {[hex(x) for x in exp0]}")
    print(f"C0 router:   top_idx={top0}, scores={[hex(s) for s in top_sc0]}")
    print(f"C1 expected: {[hex(x) for x in exp1]}")
    print(f"C1 router:   top_idx={top1}, scores={[hex(s) for s in top_sc1]}")


if __name__ == "__main__":
    main()
