`timescale 1ns/1ps
//=============================================================================
// tb_cluster_384.sv — 32-Chip / 384-Layer Cluster Simulation
//   PER-LAYER UNIQUE WEIGHTS edition
//
// Each layer gets unique router + FFN weights generated by a deterministic
// hash of the global layer index, producing varying outputs per layer.
//=============================================================================

module tb_cluster_384;
    localparam int HIDDEN    = 8;
    localparam int K_LATENT  = 4;
    localparam int V_LATENT  = 4;
    localparam int NUM_SLOTS = 64;
    localparam int MAX_POS   = 64;
    localparam int WEIGHT_W  = 16;
    localparam int DATA_W    = 32;
    localparam int LAYERS_PER_CHIP = 12;
    localparam int NUM_CHIPS = 32;
    localparam int TOTAL_LAYERS = LAYERS_PER_CHIP * NUM_CHIPS;

    logic clk, rst_n;

    // RMSNorm gamma
    logic gamma_wr_en;
    logic [2:0] gamma_wr_idx;
    logic signed [31:0] gamma_wr_data;

    // MLA Attention v2
    logic                         attn_qkv_wt_wr_en;
    logic [2:0]                   attn_qkv_wt_sel;
    logic [$clog2(HIDDEN)-1:0]    attn_qkv_wt_row;
    logic [$clog2(HIDDEN)-1:0]    attn_qkv_wt_col;
    logic signed [WEIGHT_W-1:0]   attn_qkv_wt_wr_data;

    logic                         attn_rope_lut_wr_en;
    logic [$clog2(MAX_POS)-1:0]   attn_rope_lut_pos;
    logic [$clog2(HIDDEN/2)-1:0]  attn_rope_lut_pair;
    logic signed [WEIGHT_W-1:0]   attn_rope_lut_sin;
    logic signed [WEIGHT_W-1:0]   attn_rope_lut_cos;

    logic [$clog2(MAX_POS)-1:0]   token_position;

    // Router
    logic rtr_w_wr_en;
    logic [1:0] rtr_w_wr_expert;
    logic [2:0] rtr_w_wr_idx;
    logic signed [31:0] rtr_w_wr_data;

    // FFN
    logic gate_w_wr_en, up_w_wr_en, down_w_wr_en;
    logic [1:0] gate_w_wr_row, up_w_wr_row;
    logic [2:0] down_w_wr_row;
    logic [0:0] gate_w_wr_beat, up_w_wr_beat, down_w_wr_beat;
    logic [15:0] gate_w_wr_data, up_w_wr_data, down_w_wr_data;

    // Scale
    logic scale_wr_en;
    logic [1:0] scale_wr_addr;
    logic [7:0] scale_wr_data;

    // KV cache preload (unused in this test)
    logic                         cache_preload_en;
    logic [K_LATENT*DATA_W-1:0]   cache_preload_K_flat;
    logic [V_LATENT*DATA_W-1:0]   cache_preload_V_flat;

    // Activation I/O (flat ports to DUT)
    logic valid_in, valid_out, router_ok;
    logic [HIDDEN*32-1:0] a_flat;
    logic [HIDDEN*32-1:0] y_flat;
    logic [1:0] ffn_expert_sel;            // FFN expert select for weight preload
    logic [3:0] cfg_local_experts;          // local expert bitmap

    // Convenience aliases for existing test logic
    wire signed [31:0] a0 = a_flat[0*32+:32];
    wire signed [31:0] a1 = a_flat[1*32+:32];
    wire signed [31:0] a2 = a_flat[2*32+:32];
    wire signed [31:0] a3 = a_flat[3*32+:32];
    wire signed [31:0] a4 = a_flat[4*32+:32];
    wire signed [31:0] a5 = a_flat[5*32+:32];
    wire signed [31:0] a6 = a_flat[6*32+:32];
    wire signed [31:0] a7 = a_flat[7*32+:32];

    wire signed [31:0] y0 = y_flat[0*32+:32];
    wire signed [31:0] y1 = y_flat[1*32+:32];
    wire signed [31:0] y2 = y_flat[2*32+:32];
    wire signed [31:0] y3 = y_flat[3*32+:32];
    wire signed [31:0] y4 = y_flat[4*32+:32];
    wire signed [31:0] y5 = y_flat[5*32+:32];
    wire signed [31:0] y6 = y_flat[6*32+:32];
    wire signed [31:0] y7 = y_flat[7*32+:32];

    full_transformer_layer #(
        .HIDDEN(HIDDEN), .K_LATENT(K_LATENT), .V_LATENT(V_LATENT),
        .NUM_SLOTS(NUM_SLOTS), .MAX_POS(MAX_POS),
        .WEIGHT_W(WEIGHT_W), .DATA_W(DATA_W)
    ) dut (.*);

    // Clock: 100 MHz
    initial clk = 0;
    always #5 clk = ~clk;

    //=========================================================================
    // Deterministic weight hash: w = base + ((layer*P1 + idx*P2) mod RANGE)
    //=========================================================================
    function integer hash_weight(input integer layer, input integer idx, input integer base, input integer range_val);
        begin
            hash_weight = base + ((layer * 257 + idx * 127) % range_val);
        end
    endfunction

    //=========================================================================
    // One-time weight preload (same for all layers)
    //=========================================================================
    task preload_scales;
        begin
            @(posedge clk); scale_wr_en<=1; scale_wr_addr<=0; scale_wr_data<=8'h38; @(posedge clk); scale_wr_en<=0;
            @(posedge clk); scale_wr_en<=1; scale_wr_addr<=1; scale_wr_data<=8'h38; @(posedge clk); scale_wr_en<=0;
        end
    endtask

    task preload_gamma;
        integer i;
        begin
            for (i = 0; i < 8; i = i + 1) begin
                @(posedge clk); gamma_wr_en<=1; gamma_wr_idx<=i[2:0]; gamma_wr_data<=4096; @(posedge clk); gamma_wr_en<=0;
            end
        end
    endtask

    task preload_qkv;
        integer r, c;
        begin
            for (r = 0; r < 8; r = r + 1)
                for (c = 0; c < 8; c = c + 1) begin
                    @(posedge clk); attn_qkv_wt_wr_en<=1; attn_qkv_wt_sel<=0;
                    attn_qkv_wt_row<=r[2:0]; attn_qkv_wt_col<=c[2:0];
                    attn_qkv_wt_wr_data<=(r==c)?16'sd4096:16'sd0;
                    @(posedge clk); attn_qkv_wt_wr_en<=0;
                end
            for (r = 0; r < 4; r = r + 1)
                for (c = 0; c < 8; c = c + 1) begin
                    @(posedge clk); attn_qkv_wt_wr_en<=1; attn_qkv_wt_sel<=1;
                    attn_qkv_wt_row<=r[2:0]; attn_qkv_wt_col<=c[2:0];
                    attn_qkv_wt_wr_data<=(r==c)?16'sd4096:16'sd0;
                    @(posedge clk); attn_qkv_wt_wr_en<=0;
                end
            for (r = 0; r < 8; r = r + 1)
                for (c = 0; c < 4; c = c + 1) begin
                    @(posedge clk); attn_qkv_wt_wr_en<=1; attn_qkv_wt_sel<=2;
                    attn_qkv_wt_row<=r[2:0]; attn_qkv_wt_col<=c[2:0];
                    attn_qkv_wt_wr_data<=(r==c)?16'sd4096:16'sd0;
                    @(posedge clk); attn_qkv_wt_wr_en<=0;
                end
            for (r = 0; r < 4; r = r + 1)
                for (c = 0; c < 8; c = c + 1) begin
                    @(posedge clk); attn_qkv_wt_wr_en<=1; attn_qkv_wt_sel<=3;
                    attn_qkv_wt_row<=r[2:0]; attn_qkv_wt_col<=c[2:0];
                    attn_qkv_wt_wr_data<=(r==c)?16'sd4096:16'sd0;
                    @(posedge clk); attn_qkv_wt_wr_en<=0;
                end
            for (r = 0; r < 8; r = r + 1)
                for (c = 0; c < 4; c = c + 1) begin
                    @(posedge clk); attn_qkv_wt_wr_en<=1; attn_qkv_wt_sel<=4;
                    attn_qkv_wt_row<=r[2:0]; attn_qkv_wt_col<=c[2:0];
                    attn_qkv_wt_wr_data<=(r==c)?16'sd4096:16'sd0;
                    @(posedge clk); attn_qkv_wt_wr_en<=0;
                end
        end
    endtask

    task preload_rope;
        integer p, pair;
        begin
            for (p = 0; p < MAX_POS; p = p + 1)
                for (pair = 0; pair < HIDDEN/2; pair = pair + 1) begin
                    @(posedge clk); attn_rope_lut_wr_en<=1;
                    attn_rope_lut_pos<=p[5:0]; attn_rope_lut_pair<=pair[1:0];
                    attn_rope_lut_sin<=16'sd0; attn_rope_lut_cos<=16'sd4096;
                    @(posedge clk); attn_rope_lut_wr_en<=0;
                end
        end
    endtask

    //=========================================================================
    // Per-layer weight reload (router + FFN vary by layer_id)
    //=========================================================================
    task reload_router_for_layer;
        input integer layer_id;
        integer e, i, w;
        begin
            for (e = 0; e < 4; e = e + 1) begin
                for (i = 0; i < 8; i = i + 1) begin
                    // Diagonal entries: large + layer-variant (shifts which expert wins)
                    // Off-diagonal: small + layer-variant noise
                    if (i == e) begin
                        w = 4096 + ((layer_id * 317 + e * 211) % 4096);
                    end else begin
                        w = ((layer_id * 137 + i * 73 + e * 53) % 1024);
                    end
                    @(posedge clk); rtr_w_wr_en<=1; rtr_w_wr_expert<=e[1:0];
                    rtr_w_wr_idx<=i[2:0]; rtr_w_wr_data<=w;
                    @(posedge clk); rtr_w_wr_en<=0;
                end
            end
        end
    endtask

    task reload_ffn_for_layer;
        input integer layer_id;
        integer r, lane_val;
        begin
            // Gate weights: fp4 values packed 4 per 16-bit beat
            for (r = 0; r < 4; r = r + 1) begin
                // Beat 0: lanes 0-3
                lane_val = 4 + ((layer_id * 97 + r * 67) % 8);  // fp4 range 0-7
                @(posedge clk); gate_w_wr_en<=1; gate_w_wr_row<=r[1:0]; gate_w_wr_beat<=0;
                gate_w_wr_data<={lane_val[3:0], lane_val[3:0], lane_val[3:0], lane_val[3:0]};
                @(posedge clk); gate_w_wr_en<=0;
                // Beat 1: lanes 4-7 (zero for HIDDEN=8 with LANES=4, only 4 INTER dims)
                @(posedge clk); gate_w_wr_en<=1; gate_w_wr_row<=r[1:0]; gate_w_wr_beat<=1;
                gate_w_wr_data<=16'h0;
                @(posedge clk); gate_w_wr_en<=0;

                // Up weights: same pattern
                lane_val = 4 + ((layer_id * 151 + r * 89) % 8);
                @(posedge clk); up_w_wr_en<=1; up_w_wr_row<=r[1:0]; up_w_wr_beat<=0;
                up_w_wr_data<={lane_val[3:0], lane_val[3:0], lane_val[3:0], lane_val[3:0]};
                @(posedge clk); up_w_wr_en<=0;
                @(posedge clk); up_w_wr_en<=1; up_w_wr_row<=r[1:0]; up_w_wr_beat<=1;
                up_w_wr_data<=16'h0;
                @(posedge clk); up_w_wr_en<=0;
            end
        end
    endtask

    task preload_ffn_down;
        integer r;
        begin
            // Down projection (4→8): each intermediate maps to TWO output dims
            //   int0 → out0, out4
            //   int1 → out1, out5
            //   int2 → out2, out6
            //   int3 → out3, out7
            // First 4 rows: identity (intX → outX)
            @(posedge clk); down_w_wr_en<=1; down_w_wr_row<=0; down_w_wr_beat<=0;
            down_w_wr_data<={4'h0,4'h0,4'h0,4'h4}; @(posedge clk); down_w_wr_en<=0;
            @(posedge clk); down_w_wr_en<=1; down_w_wr_row<=1; down_w_wr_beat<=0;
            down_w_wr_data<={4'h0,4'h0,4'h4,4'h0}; @(posedge clk); down_w_wr_en<=0;
            @(posedge clk); down_w_wr_en<=1; down_w_wr_row<=2; down_w_wr_beat<=0;
            down_w_wr_data<={4'h0,4'h4,4'h0,4'h0}; @(posedge clk); down_w_wr_en<=0;
            @(posedge clk); down_w_wr_en<=1; down_w_wr_row<=3; down_w_wr_beat<=0;
            down_w_wr_data<={4'h4,4'h0,4'h0,4'h0}; @(posedge clk); down_w_wr_en<=0;
            // Rows 4-7: repeat (intX → outX+4)
            @(posedge clk); down_w_wr_en<=1; down_w_wr_row<=4; down_w_wr_beat<=0;
            down_w_wr_data<={4'h0,4'h0,4'h0,4'h4}; @(posedge clk); down_w_wr_en<=0;
            @(posedge clk); down_w_wr_en<=1; down_w_wr_row<=5; down_w_wr_beat<=0;
            down_w_wr_data<={4'h0,4'h0,4'h4,4'h0}; @(posedge clk); down_w_wr_en<=0;
            @(posedge clk); down_w_wr_en<=1; down_w_wr_row<=6; down_w_wr_beat<=0;
            down_w_wr_data<={4'h0,4'h4,4'h0,4'h0}; @(posedge clk); down_w_wr_en<=0;
            @(posedge clk); down_w_wr_en<=1; down_w_wr_row<=7; down_w_wr_beat<=0;
            down_w_wr_data<={4'h4,4'h0,4'h0,4'h0}; @(posedge clk); down_w_wr_en<=0;
        end
    endtask

    //=========================================================================
    // Run one layer
    //=========================================================================
    integer layer_start_cycle;
    integer layer_latency;

    task run_one_layer;
        input integer layer_id;
        begin
            layer_start_cycle = $time / 10;
            token_position <= layer_id % MAX_POS;
            @(posedge clk); #1;
            valid_in <= 1;
            @(posedge clk); #1;
            valid_in <= 0;

            layer_latency = 0;
            while (!valid_out) begin
                @(posedge clk);
                layer_latency = layer_latency + 1;
                if (layer_latency > 5000) begin
                    $error("Layer %0d: TIMEOUT after %0d cycles", layer_id, layer_latency);
                    $fatal;
                end
            end
            #1;
            layer_latency = ($time / 10) - layer_start_cycle;
        end
    endtask

    //=========================================================================
    // Main
    //=========================================================================
    integer chip, layer, global_layer, d;
    integer chip_lat [0:NUM_CHIPS-1];
    integer cluster_total_lat;
    reg [31:0] tok [0:7];
    reg [31:0] first_output [0:7];
    reg [31:0] last_output [0:7];
    // Save a few intermediate outputs to show variation
    reg [31:0] snap_l0  [0:7];
    reg [31:0] snap_l1  [0:7];
    reg [31:0] snap_l10 [0:7];
    reg [31:0] snap_l100[0:7];
    reg [31:0] snap_l200[0:7];
    reg [31:0] snap_l300[0:7];

    initial begin
        // Init
        rst_n = 0;
        gamma_wr_en <= 0; attn_qkv_wt_wr_en <= 0; attn_rope_lut_wr_en <= 0;
        rtr_w_wr_en <= 0; gate_w_wr_en <= 0; up_w_wr_en <= 0; down_w_wr_en <= 0;
        scale_wr_en <= 0; valid_in <= 0; token_position <= '0;
        cache_preload_en <= 0; cache_preload_K_flat <= '0; cache_preload_V_flat <= '0;
        ffn_expert_sel <= 0; cfg_local_experts <= '1;
        repeat (5) @(posedge clk); rst_n = 1;
        repeat (2) @(posedge clk);

        $display("======================================================================");
        $display(" FPGA LPU — 32-Chip / 384-Layer Cluster Simulation");
        $display("            PER-LAYER UNIQUE WEIGHTS");
        $display("======================================================================");
        $display(" Chips:          %0d", NUM_CHIPS);
        $display(" Layers/chip:    %0d", LAYERS_PER_CHIP);
        $display(" Total layers:   %0d", TOTAL_LAYERS);
        $display(" Weights:        Router + FFN vary per layer (deterministic hash)");
        $display("                 QKV + Gamma + RoPE = identity (all layers same)");
        $display("======================================================================");
        $display("");

        //---------------------------------------------------------------------
        // One-time weight preload (shared across all layers)
        //---------------------------------------------------------------------
        $display("[PRELOAD] Loading shared weights...");
        preload_scales;
        preload_gamma;
        $display("  Gamma + Scales: loaded.");
        preload_qkv;
        $display("  QKV (identity): 192 weights.");
        preload_rope;
        $display("  RoPE LUT:       512 entries.");
        preload_ffn_down;
        $display("  FFN down:       8 rows.");
        $display("");

        //---------------------------------------------------------------------
        // Initial token
        //---------------------------------------------------------------------
        tok[0] = 4096; tok[1] = 4096; tok[2] = 4096; tok[3] = 4096;
        tok[4] = 4096; tok[5] = 4096; tok[6] = 4096; tok[7] = 4096;

        $display("[INPUT]  L_initial: [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 tok[0], tok[1], tok[2], tok[3], tok[4], tok[5], tok[6], tok[7]);
        $display("");

        //---------------------------------------------------------------------
        // Run all 384 layers
        //---------------------------------------------------------------------
        cluster_total_lat = 0;
        for (chip = 0; chip < NUM_CHIPS; chip = chip + 1) begin
            chip_lat[chip] = 0;

            if (chip < 2 || chip >= NUM_CHIPS-2)
                $display("--- Chip %0d (global layers %0d..%0d) ---",
                         chip, chip*LAYERS_PER_CHIP, (chip+1)*LAYERS_PER_CHIP-1);
            else if (chip == 2)
                $display("  ... chips 2..%0d ...", NUM_CHIPS-3);

            for (layer = 0; layer < LAYERS_PER_CHIP; layer = layer + 1) begin
                global_layer = chip * LAYERS_PER_CHIP + layer;

                // ---- Per-layer weight reload ----
                reload_router_for_layer(global_layer);
                reload_ffn_for_layer(global_layer);

                // ---- Feed token ----
                for (int d = 0; d < 8; d++) a_flat[d*32+:32] = tok[d];

                run_one_layer(global_layer);
                chip_lat[chip] = chip_lat[chip] + layer_latency;

                // Capture output
                tok[0] = y0; tok[1] = y1; tok[2] = y2; tok[3] = y3;
                tok[4] = y4; tok[5] = y5; tok[6] = y6; tok[7] = y7;

                // Save snapshots
                if (global_layer == 0) begin
                    snap_l0[0]=tok[0]; snap_l0[1]=tok[1]; snap_l0[2]=tok[2]; snap_l0[3]=tok[3];
                    snap_l0[4]=tok[4]; snap_l0[5]=tok[5]; snap_l0[6]=tok[6]; snap_l0[7]=tok[7];
                end
                if (global_layer == 1) begin
                    snap_l1[0]=tok[0]; snap_l1[1]=tok[1]; snap_l1[2]=tok[2]; snap_l1[3]=tok[3];
                    snap_l1[4]=tok[4]; snap_l1[5]=tok[5]; snap_l1[6]=tok[6]; snap_l1[7]=tok[7];
                end
                if (global_layer == 10) begin
                    snap_l10[0]=tok[0]; snap_l10[1]=tok[1]; snap_l10[2]=tok[2]; snap_l10[3]=tok[3];
                    snap_l10[4]=tok[4]; snap_l10[5]=tok[5]; snap_l10[6]=tok[6]; snap_l10[7]=tok[7];
                end
                if (global_layer == 100) begin
                    snap_l100[0]=tok[0]; snap_l100[1]=tok[1]; snap_l100[2]=tok[2]; snap_l100[3]=tok[3];
                    snap_l100[4]=tok[4]; snap_l100[5]=tok[5]; snap_l100[6]=tok[6]; snap_l100[7]=tok[7];
                end
                if (global_layer == 200) begin
                    snap_l200[0]=tok[0]; snap_l200[1]=tok[1]; snap_l200[2]=tok[2]; snap_l200[3]=tok[3];
                    snap_l200[4]=tok[4]; snap_l200[5]=tok[5]; snap_l200[6]=tok[6]; snap_l200[7]=tok[7];
                end
                if (global_layer == 300) begin
                    snap_l300[0]=tok[0]; snap_l300[1]=tok[1]; snap_l300[2]=tok[2]; snap_l300[3]=tok[3];
                    snap_l300[4]=tok[4]; snap_l300[5]=tok[5]; snap_l300[6]=tok[6]; snap_l300[7]=tok[7];
                end

                // Show first and last layer of first and last chips
                if ((chip < 2 || chip >= NUM_CHIPS-2) &&
                    (layer == 0 || layer == LAYERS_PER_CHIP-1)) begin
                    $display("  L%-4d: [%0d %0d %0d %0d %0d %0d %0d %0d] (%0d cyc)",
                             global_layer,
                             tok[0], tok[1], tok[2], tok[3],
                             tok[4], tok[5], tok[6], tok[7],
                             layer_latency);
                end

                if (global_layer == 0) begin
                    first_output[0]=tok[0]; first_output[1]=tok[1];
                    first_output[2]=tok[2]; first_output[3]=tok[3];
                    first_output[4]=tok[4]; first_output[5]=tok[5];
                    first_output[6]=tok[6]; first_output[7]=tok[7];
                end
                if (global_layer == TOTAL_LAYERS-1) begin
                    last_output[0]=tok[0]; last_output[1]=tok[1];
                    last_output[2]=tok[2]; last_output[3]=tok[3];
                    last_output[4]=tok[4]; last_output[5]=tok[5];
                    last_output[6]=tok[6]; last_output[7]=tok[7];
                end
            end
            cluster_total_lat = cluster_total_lat + chip_lat[chip];
        end

        //---------------------------------------------------------------------
        // Results
        //---------------------------------------------------------------------
        $display("");
        $display("======================================================================");
        $display(" CLUSTER SIMULATION COMPLETE");
        $display("======================================================================");
        $display("");
        $display(" Token value progression across layers:");
        $display("   Input:    [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 4096,4096,4096,4096,4096,4096,4096,4096);
        $display("   After L0:   [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 snap_l0[0],snap_l0[1],snap_l0[2],snap_l0[3],
                 snap_l0[4],snap_l0[5],snap_l0[6],snap_l0[7]);
        $display("   After L1:   [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 snap_l1[0],snap_l1[1],snap_l1[2],snap_l1[3],
                 snap_l1[4],snap_l1[5],snap_l1[6],snap_l1[7]);
        $display("   After L10:  [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 snap_l10[0],snap_l10[1],snap_l10[2],snap_l10[3],
                 snap_l10[4],snap_l10[5],snap_l10[6],snap_l10[7]);
        $display("   After L100: [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 snap_l100[0],snap_l100[1],snap_l100[2],snap_l100[3],
                 snap_l100[4],snap_l100[5],snap_l100[6],snap_l100[7]);
        $display("   After L200: [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 snap_l200[0],snap_l200[1],snap_l200[2],snap_l200[3],
                 snap_l200[4],snap_l200[5],snap_l200[6],snap_l200[7]);
        $display("   After L300: [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 snap_l300[0],snap_l300[1],snap_l300[2],snap_l300[3],
                 snap_l300[4],snap_l300[5],snap_l300[6],snap_l300[7]);
        $display("   Final L383: [%0d %0d %0d %0d %0d %0d %0d %0d]",
                 last_output[0],last_output[1],last_output[2],last_output[3],
                 last_output[4],last_output[5],last_output[6],last_output[7]);
        $display("");

        $display(" Per-chip latency:");
        for (chip = 0; chip < NUM_CHIPS; chip = chip + 1) begin
            if (chip < 4 || chip >= NUM_CHIPS-4) begin
                $display("   Chip %2d: %6d cycles  (%7.2f us)",
                         chip, chip_lat[chip], chip_lat[chip] * 0.01);
            end else if (chip == 4) begin
                $display("   ...");
            end
        end

        $display("");
        $display(" Cluster total latency: %0d cycles", cluster_total_lat);
        $display("   = %.2f us", cluster_total_lat * 0.01);
        $display("   = %.2f ms", cluster_total_lat * 0.00001);
        $display("");
        if (cluster_total_lat > 0) begin
            $display(" Throughput at 100 MHz:  %.1f tokens/s", 1.0e8 / cluster_total_lat);
        end
        $display("");
        $display(" PASS: 1 token through %0d layers across %0d chips (varying weights)",
                 TOTAL_LAYERS, NUM_CHIPS);
        $display("======================================================================");
        $finish;
    end

    // Watchdog
    initial begin
        #500000000;
        $error("WATCHDOG TIMEOUT");
        $finish;
    end

endmodule
