// AUTO-GENERATED by scripts/simulation/gen_ffn_tb_vectors.py
package tb_ffn_golden_pkg;
    localparam int HIDDEN = 8;
    localparam int INTER = 4;
    localparam int LANES = 4;
    localparam int K_BEATS = 2;

    localparam logic [64-1:0] C0_ACT_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [128-1:0] C0_GATE_W_PACK = {4'h0, 4'h0, 4'h0, 4'h0, 4'h1, 4'h1, 4'h1, 4'h1, 4'h0, 4'h0, 4'h0, 4'h0, 4'h1, 4'h1, 4'h1, 4'h1, 4'h0, 4'h0, 4'h0, 4'h0, 4'h1, 4'h1, 4'h1, 4'h1, 4'h0, 4'h0, 4'h0, 4'h0, 4'h1, 4'h1, 4'h1, 4'h1};
    localparam logic [128-1:0] C0_UP_W_PACK = {4'h0, 4'h0, 4'h0, 4'h0, 4'h1, 4'h1, 4'h1, 4'h1, 4'h0, 4'h0, 4'h0, 4'h0, 4'h1, 4'h1, 4'h1, 4'h1, 4'h0, 4'h0, 4'h0, 4'h0, 4'h1, 4'h1, 4'h1, 4'h1, 4'h0, 4'h0, 4'h0, 4'h0, 4'h1, 4'h1, 4'h1, 4'h1};
    localparam logic [128-1:0] C0_DOWN_W_PACK = {4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4};
    localparam logic [256-1:0] C0_EXPECTED_PACK = {32'h00000000, 32'h00000000, 32'h00000000, 32'h00000000, 32'h00000c00, 32'h00000c00, 32'h00000c00, 32'h00000c00};

    localparam logic [64-1:0] C1_ACT_PACK = {8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'hb8, 8'h38};
    localparam logic [128-1:0] C1_GATE_W_PACK = {4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'hc, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'hc, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4};
    localparam logic [128-1:0] C1_UP_W_PACK = {4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'hc, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4};
    localparam logic [128-1:0] C1_DOWN_W_PACK = {4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4, 4'h0, 4'h0, 4'h0, 4'h0, 4'h4};
    localparam logic [256-1:0] C1_EXPECTED_PACK = {32'h00000000, 32'h00000000, 32'h00000000, 32'h00000000, 32'hfffff400, 32'hfffffc00, 32'hfffffc00, 32'h00000c00};
endpackage
