//=============================================================================
// tb_fp4_mac.sv — Self-checking testbench for fp4_mac module
//
// Golden reference values generated by scripts/simulation/gen_tb_vectors.py
// (independent Python model — no shared code with RTL).
//
// Usage (Questa/ModelSim):
//   vlib work
//   vlog +incdir+../include ../dsp/fp4_mac.sv tb_fp4_mac.sv
//   vsim -c -do "run -all; quit" tb_fp4_mac
//=============================================================================

`include "fp4_types.svh"
`include "tb_golden_pkg.sv"

module tb_fp4_mac;

    localparam int CLK_PERIOD = 10;  // 100 MHz
    localparam int PIPELINE_DEPTH = 6;  // drain cycles (4-stage pipeline + margin)

    logic            clk;
    logic            rst_n;
    logic            accum_clr;
    fp4_mac_input_t  mac_in;
    fp4_mac_output_t mac_out;

    fp4_mac #(.ACCUM_WIDTH(32), .VEC_LANES(2)) dut (.*);

    // Clock
    always #(CLK_PERIOD/2) clk = ~clk;

    //----------------------------------------------------------------------------
    // Drive a single (weight, activation) pair. Blocking assigns, valid=1 pulse.
    //----------------------------------------------------------------------------
    task automatic drive(input logic [3:0] w, input logic [7:0] a, input logic [7:0] s = 8'h38);
        mac_in.weight = w;
        mac_in.scale  = fp8_to_scaled12(s);  // pre-decode at drive time
        mac_in.activ  = a;
        mac_in.valid  = 1'b1;
        @(posedge clk);
        mac_in.valid  = 1'b0;
    endtask

    //----------------------------------------------------------------------------
    // Drive a sequence back-to-back (valid stays high throughout).
    //----------------------------------------------------------------------------
    task automatic drive_stream(
        input logic [3:0] weights [],
        input logic [7:0] activs [],
        input logic [7:0] scales []
    );
        for (int i = 0; i < weights.size(); i++) begin
            mac_in.weight = weights[i];
            mac_in.scale  = fp8_to_scaled12(scales[i]);
            mac_in.activ  = activs[i];
            mac_in.valid  = 1'b1;
            @(posedge clk);
        end
        mac_in.valid = 1'b0;
    endtask

    //----------------------------------------------------------------------------
    // Drain pipeline and check accumulator against expected.
    //----------------------------------------------------------------------------
    integer pass_count = 0;
    integer fail_count = 0;

    task automatic check_result(
        input logic [31:0] expected,
        input string        test_name
    );
        // Wait for pipeline to drain
        repeat (PIPELINE_DEPTH) @(posedge clk);
        if (mac_out.result !== expected) begin
            $error("[FAIL] %s", test_name);
            $error("       got:      0x%08h (%0d)", mac_out.result, mac_out.result);
            $error("       expected: 0x%08h (%0d)", expected, expected);
            $error("       diff:     0x%08h", mac_out.result - expected);
            fail_count++;
        end else begin
            $display("[ OK ] %s  (0x%08h)", test_name, mac_out.result);
            pass_count++;
        end
    endtask

    //----------------------------------------------------------------------------
    // Run a single test: drive sequence, check result.
    //----------------------------------------------------------------------------
    task automatic run_test(
        input int           len,
        input logic [255:0] weights_pack,
        input logic [511:0] activs_pack,
        input logic [511:0] scales_pack,
        input logic [31:0]  expected,
        input string        test_name,
        input bit           use_stream = 1'b0
    );
        // Clear accumulator
        accum_clr = 1'b1;
        @(posedge clk);
        accum_clr = 1'b0;

        // Drive inputs (packed element 0 in low bits)
        for (int i = 0; i < len; i++) begin
            drive(weights_pack[i*4 +: 4], activs_pack[i*8 +: 8], scales_pack[i*8 +: 8]);
        end

        // Check
        check_result(expected, test_name);
    endtask

    //----------------------------------------------------------------------------
    // Test sequence
    //----------------------------------------------------------------------------
    initial begin
        clk       = 1'b0;
        rst_n     = 1'b0;
        accum_clr = 1'b0;
        mac_in    = '0;

        repeat (5) @(posedge clk);
        rst_n = 1'b1;
        repeat (2) @(posedge clk);

        $display("============================================================");
        $display(" tb_fp4_mac — Golden Vector Verification");
        $display("============================================================");
        $display(" Pipeline: 3-stage, %0d tests from tb_golden_pkg", tb_golden_pkg::NUM_TESTS);
        $display("============================================================");
        $display("");

        // Run each test from golden package
        run_test(tb_golden_pkg::T0_LEN, tb_golden_pkg::T0_W_PACK, tb_golden_pkg::T0_A_PACK, tb_golden_pkg::T0_S_PACK, tb_golden_pkg::T0_EXPECTED,  "T1  single multiply        ");
        run_test(tb_golden_pkg::T1_LEN, tb_golden_pkg::T1_W_PACK, tb_golden_pkg::T1_A_PACK, tb_golden_pkg::T1_S_PACK, tb_golden_pkg::T1_EXPECTED,  "T2  4-term accumulation    ");
        run_test(tb_golden_pkg::T2_LEN, tb_golden_pkg::T2_W_PACK, tb_golden_pkg::T2_A_PACK, tb_golden_pkg::T2_S_PACK, tb_golden_pkg::T2_EXPECTED,  "T3  pos fp4 sweep (x8)     ");
        run_test(tb_golden_pkg::T3_LEN, tb_golden_pkg::T3_W_PACK, tb_golden_pkg::T3_A_PACK, tb_golden_pkg::T3_S_PACK, tb_golden_pkg::T3_EXPECTED,  "T4  neg fp4 sweep (x7)     ");
        run_test(tb_golden_pkg::T4_LEN, tb_golden_pkg::T4_W_PACK, tb_golden_pkg::T4_A_PACK, tb_golden_pkg::T4_S_PACK, tb_golden_pkg::T4_EXPECTED,  "T5  mixed signs            ");
        run_test(tb_golden_pkg::T5_LEN, tb_golden_pkg::T5_W_PACK, tb_golden_pkg::T5_A_PACK, tb_golden_pkg::T5_S_PACK, tb_golden_pkg::T5_EXPECTED,  "T6  zeros                  ");
        run_test(tb_golden_pkg::T6_LEN, tb_golden_pkg::T6_W_PACK, tb_golden_pkg::T6_A_PACK, tb_golden_pkg::T6_S_PACK, tb_golden_pkg::T6_EXPECTED,  "T7  fp8 subnorm            ");
        run_test(tb_golden_pkg::T7_LEN, tb_golden_pkg::T7_W_PACK, tb_golden_pkg::T7_A_PACK, tb_golden_pkg::T7_S_PACK, tb_golden_pkg::T7_EXPECTED,  "T8  fp8 e=1 edge           ");
        run_test(tb_golden_pkg::T8_LEN, tb_golden_pkg::T8_W_PACK, tb_golden_pkg::T8_A_PACK, tb_golden_pkg::T8_S_PACK, tb_golden_pkg::T8_EXPECTED,  "T9  fp8 saturation edge    ");
        run_test(tb_golden_pkg::T9_LEN, tb_golden_pkg::T9_W_PACK, tb_golden_pkg::T9_A_PACK, tb_golden_pkg::T9_S_PACK, tb_golden_pkg::T9_EXPECTED,  "T10 32-term max accum      ");
        run_test(tb_golden_pkg::T10_LEN, tb_golden_pkg::T10_W_PACK, tb_golden_pkg::T10_A_PACK, tb_golden_pkg::T10_S_PACK, tb_golden_pkg::T10_EXPECTED, "T11 16-stream (no bubble)  ");
        run_test(tb_golden_pkg::T11_LEN, tb_golden_pkg::T11_W_PACK, tb_golden_pkg::T11_A_PACK, tb_golden_pkg::T11_S_PACK, tb_golden_pkg::T11_EXPECTED, "T12 sign cancellation (x16)");
        run_test(tb_golden_pkg::T12_LEN, tb_golden_pkg::T12_W_PACK, tb_golden_pkg::T12_A_PACK, tb_golden_pkg::T12_S_PACK, tb_golden_pkg::T12_EXPECTED, "T13 fp8 exponent sweep     ");
        run_test(tb_golden_pkg::T13_LEN, tb_golden_pkg::T13_W_PACK, tb_golden_pkg::T13_A_PACK, tb_golden_pkg::T13_S_PACK, tb_golden_pkg::T13_EXPECTED, "T14 non-unity scale        ");

        //--------------------------------------------------------------------
        // Dynamic test: accum_clr during streaming
        //--------------------------------------------------------------------
        begin
            logic signed [31:0] part1, part2;

            $display("");
            $display("--- Dynamic: accum_clr mid-stream ---");

            // First accumulation
            accum_clr = 1'b1; @(posedge clk); accum_clr = 1'b0;
            drive(4'b0100, 8'h38);  // +1.0 x +1.0 = 4096
            drive(4'b0100, 8'h38);  // +1.0 x +1.0 = 4096
            repeat (PIPELINE_DEPTH) @(posedge clk);
            part1 = mac_out.result;
            $display("  After 2 terms: 0x%08h (expect 0x%08h)", part1, 32'h2000);

            // Clear and start fresh
            accum_clr = 1'b1; @(posedge clk); accum_clr = 1'b0;
            drive(4'b0110, 8'h38);  // +2.0 x +1.0 = 8192
            drive(4'b0110, 8'h38);  // +2.0 x +1.0 = 8192
            repeat (PIPELINE_DEPTH) @(posedge clk);
            part2 = mac_out.result;
            $display("  After clear + 2 terms: 0x%08h (expect 0x%08h)", part2, 32'h4000);

            if (part1 === 32'h2000 && part2 === 32'h4000) begin
                $display("[ OK ] Dynamic accum_clr test");
                pass_count++;
            end else begin
                $error("[FAIL] Dynamic accum_clr test");
                fail_count++;
            end
        end

        //--------------------------------------------------------------------
        // Results
        //--------------------------------------------------------------------
        $display("");
        $display("============================================================");
        if (fail_count == 0)
            $display(" ALL %0d TESTS PASSED", pass_count);
        else
            $display(" %0d PASSED, %0d FAILED", pass_count, fail_count);
        $display("============================================================");

        if (fail_count != 0)
            $fatal(1, "Testbench failed");
        $finish;
    end

    // Watchdog
    initial begin
        #500000;
        $error("TIMEOUT — simulation did not finish within 500us");
        $finish;
    end

endmodule
