//=============================================================================
// tb_golden_pkg.sv ¡ª AUTO-GENERATED by gen_tb_vectors.py
// Golden reference values for tb_fp4_mac.sv
// DO NOT EDIT BY HAND
//=============================================================================

package tb_golden_pkg;

    localparam int NUM_TESTS = 14;

    // T1_SINGLE: fp4 +1.0 x fp8 +1.0 (1 terms)
    localparam int T0_LEN = 1;
    localparam logic [1*4-1:0] T0_W_PACK = {4'h4};
    localparam logic [1*8-1:0] T0_A_PACK = {8'h38};
    localparam logic [1*8-1:0] T0_S_PACK = {8'h38};
    localparam logic [31:0] T0_EXPECTED = 32'h00001000;

    // T2_ACCUM4: 4-term accumulation (4 terms)
    localparam int T1_LEN = 4;
    localparam logic [4*4-1:0] T1_W_PACK = {4'h5, 4'h5, 4'h2, 4'h2};
    localparam logic [4*8-1:0] T1_A_PACK = {8'h28, 8'h28, 8'h30, 8'h30};
    localparam logic [4*8-1:0] T1_S_PACK = {8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T1_EXPECTED = 32'h00001400;

    // T3_POS_SWEEP: all 8 positive fp4 x +1.0 (8 terms)
    localparam int T2_LEN = 8;
    localparam logic [8*4-1:0] T2_W_PACK = {4'h7, 4'h6, 4'h5, 4'h4, 4'h3, 4'h2, 4'h1, 4'h0};
    localparam logic [8*8-1:0] T2_A_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [8*8-1:0] T2_S_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T2_EXPECTED = 32'h00009000;

    // T4_NEG_SWEEP: all 7 negative fp4 x +1.0 (7 terms)
    localparam int T3_LEN = 7;
    localparam logic [7*4-1:0] T3_W_PACK = {4'hf, 4'he, 4'hd, 4'hc, 4'hb, 4'ha, 4'h9};
    localparam logic [7*8-1:0] T3_A_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [7*8-1:0] T3_S_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T3_EXPECTED = 32'hffff7000;

    // T5_MIXED_SIGN: positive + negative cancellation (2 terms)
    localparam int T4_LEN = 2;
    localparam logic [2*4-1:0] T4_W_PACK = {4'h6, 4'hc};
    localparam logic [2*8-1:0] T4_A_PACK = {8'hb0, 8'h38};
    localparam logic [2*8-1:0] T4_S_PACK = {8'h38, 8'h38};
    localparam logic [31:0] T4_EXPECTED = 32'hffffe000;

    // T6_ZEROS: fp4 zero, fp4 signed zero, fp8 zero (3 terms)
    localparam int T5_LEN = 3;
    localparam logic [3*4-1:0] T5_W_PACK = {4'h4, 4'h8, 4'h0};
    localparam logic [3*8-1:0] T5_A_PACK = {8'h00, 8'h38, 8'h38};
    localparam logic [3*8-1:0] T5_S_PACK = {8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T5_EXPECTED = 32'h00000000;

    // T7_SUBNORM: fp8 subnorm values (3 terms)
    localparam int T6_LEN = 3;
    localparam logic [3*4-1:0] T6_W_PACK = {4'h4, 4'h4, 4'h4};
    localparam logic [3*8-1:0] T6_A_PACK = {8'h07, 8'h04, 8'h01};
    localparam logic [3*8-1:0] T6_S_PACK = {8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T6_EXPECTED = 32'h00000050;

    // T8_E1_EDGE: fp8 e=1 right-shift boundary (4 terms)
    localparam int T7_LEN = 4;
    localparam logic [4*4-1:0] T7_W_PACK = {4'h4, 4'h4, 4'h4, 4'h4};
    localparam logic [4*8-1:0] T7_A_PACK = {8'h0f, 8'h0e, 8'h09, 8'h08};
    localparam logic [4*8-1:0] T7_S_PACK = {8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T7_EXPECTED = 32'h00000160;

    // T9_SAT_EDGE: fp8 near and at saturation (3 terms)
    localparam int T8_LEN = 3;
    localparam logic [3*4-1:0] T8_W_PACK = {4'h4, 4'h4, 4'h4};
    localparam logic [3*8-1:0] T8_A_PACK = {8'h50, 8'h4f, 8'h48};
    localparam logic [3*8-1:0] T8_S_PACK = {8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T8_EXPECTED = 32'h000137f0;

    // T10_LARGE_ACCUM: 32-term max-weight accumulation (32 terms)
    localparam int T9_LEN = 32;
    localparam logic [32*4-1:0] T9_W_PACK = {4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7, 4'h7};
    localparam logic [32*8-1:0] T9_A_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [32*8-1:0] T9_S_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T9_EXPECTED = 32'h00060000;

    // T11_STREAM: 16 back-to-back, no bubbles (16 terms)
    localparam int T10_LEN = 16;
    localparam logic [16*4-1:0] T10_W_PACK = {4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4};
    localparam logic [16*8-1:0] T10_A_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [16*8-1:0] T10_S_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T10_EXPECTED = 32'h00010000;

    // T12_CANCEL: alternating +2.0/-2.0 x +1.0 -> 0 (16 terms)
    localparam int T11_LEN = 16;
    localparam logic [16*4-1:0] T11_W_PACK = {4'he, 4'h6, 4'he, 4'h6, 4'he, 4'h6, 4'he, 4'h6, 4'he, 4'h6, 4'he, 4'h6, 4'he, 4'h6, 4'he, 4'h6};
    localparam logic [16*8-1:0] T11_A_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [16*8-1:0] T11_S_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T11_EXPECTED = 32'h00000000;

    // T13_FP8_SWEEP: fp8 exponents 0..7 (8 terms)
    localparam int T12_LEN = 8;
    localparam logic [8*4-1:0] T12_W_PACK = {4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4, 4'h4};
    localparam logic [8*8-1:0] T12_A_PACK = {8'h38, 8'h30, 8'h28, 8'h20, 8'h18, 8'h10, 8'h08, 8'h00};
    localparam logic [8*8-1:0] T12_S_PACK = {8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [31:0] T12_EXPECTED = 32'h00001fc0;

    // T14_SCALE: non-unity fp8 scale values (4 terms)
    localparam int T13_LEN = 4;
    localparam logic [4*4-1:0] T13_W_PACK = {4'h6, 4'h6, 4'h4, 4'h4};
    localparam logic [4*8-1:0] T13_A_PACK = {8'h38, 8'h38, 8'h38, 8'h38};
    localparam logic [4*8-1:0] T13_S_PACK = {8'h30, 8'h40, 8'h30, 8'h40};
    localparam logic [31:0] T13_EXPECTED = 32'h00007800;

endpackage